/**
 * Every empty state names one primary next action (ST-05, EPIC-01, v9.6, BLG-FE-181)
 *
 * Design source: docs/design/2026-09-21__release-v9.6/empty-state-next-action/decision_record.md §2, §5
 * Spec: docs/specs/frontend/design_system.md v1.21 §Data States ("Next-action rule")
 *
 * AC: "0 audited empty states without a next-action link". The audit is the AUDIT table below —
 * the build-time re-run of `grep -rn emptyHeading src` — and this file makes it measurable:
 *   SC-ESN-00  the audit table covers EVERY `emptyHeading` call site under src/ (a new, unaudited
 *              empty state fails here), and the two exclusions carry their stated reason
 *   SC-ESN-01…10  each page/section empty state renders exactly ONE primary action to the right place
 *   SC-ESN-11  each of the 9 dashboard cards' empty state is covered by the card's own `to` link
 *
 * Infrastructure: Playwright page.route() network interception. No live backend required.
 * ROUTING NOTE: App uses HashRouter — navigate via page.goto('/#/…').
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { test, expect } = require('@playwright/test');

const API = 'http://localhost:8000';
const json = (body, status = 200) => ({ status, contentType: 'application/json', body: JSON.stringify(body) });
const SRC = path.join(__dirname, '..', '..', 'src');

// ---------------------------------------------------------------------------
// The audit (decision_record.md §2.3, re-run at build time — 20 call sites)
//   kind: page   -> DataState `emptyAction` inside the empty region
//         card   -> the enclosing DashboardCard's own `to` link
//         excluded -> no user action could populate it (reason mandatory, §2.2)
// ---------------------------------------------------------------------------
const AUDIT = [
  { file: 'pages/Positions.js', heading: 'No open positions', kind: 'page', action: 'Enter First Position', existing: true },
  { file: 'pages/Screener.js', heading: 'No screener results yet', kind: 'page', action: 'Run Screener', existing: true },
  { file: 'pages/Watchlist.js', heading: 'Your watchlist is empty', kind: 'page', action: 'Add Ticker', existing: true },
  { file: 'pages/TradePlans.js', heading: 'No trade plans yet', kind: 'page', action: 'New Trade Plan', existing: true },
  { file: 'pages/Notifications.js', heading: 'No notifications yet', kind: 'page', action: 'Review alert settings' },
  { file: 'pages/Screener.js', heading: 'No regime history yet', kind: 'page', action: 'Run the screener' },
  { file: 'pages/PerformanceAnalytics.js', heading: 'Not enough trades', kind: 'page', action: 'Log a trade' },
  { file: 'components/trades/CalendarView.js', heading: 'No closed trades yet', kind: 'page', action: 'View open positions' },
  { file: 'components/analytics/TradePlanCompletionRateSection.js', heading: 'No trade plans created yet', kind: 'page', action: 'Create a trade plan' },
  { file: 'components/dashboard/home/PortfolioHeatCard.js', heading: 'No portfolio heat data', kind: 'card', to: '/RiskDashboard', title: 'Portfolio Heat' },
  { file: 'components/dashboard/home/RecentActivityCard.js', heading: 'No recent activity', kind: 'card', to: '/TradeHistory', title: 'Recent Activity' },
  { file: 'components/dashboard/home/OpenPositionsCard.js', heading: 'No open positions', kind: 'card', to: '/Positions', title: 'Open Positions' },
  { file: 'components/dashboard/home/GracePeriodCard.js', heading: 'No positions in grace', kind: 'card', to: '/RiskDashboard', title: 'In Grace Today' },
  { file: 'components/dashboard/home/morning/ExitZoneCard.js', heading: 'No positions to watch', kind: 'card', to: '/Positions', title: 'Positions to Watch' },
  { file: 'components/dashboard/home/morning/ScreenerHitsCard.js', heading: 'No new signals', kind: 'card', to: '/Screener', title: 'Screener Hits' },
  { file: 'components/dashboard/home/morning/RedFlagsCard.js', heading: 'No red flags this week', kind: 'card', to: '/RedFlagJournal', title: 'Red Flags' },
  { file: 'components/dashboard/home/morning/EarningsAlertCard.js', heading: 'No earnings in 7 days', kind: 'card', to: '/Positions', title: 'Earnings' },
  { file: 'components/dashboard/home/morning/ComplianceCard.js', heading: 'No compliance data yet', kind: 'card', to: '/PerformanceAnalytics', title: 'Signal Compliance' },
  { file: 'components/dashboard/home/AiDailyBriefing.js', heading: 'No briefing for today', kind: 'excluded',
    reason: 'generated by the system; no user action produces it' },
  { file: 'components/dashboard/home/WhatsNewCard.js', heading: 'Nothing to show', kind: 'excluded',
    reason: 'release-notes feed, system-populated' },
];

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(path.join(dir, e.name)) : e.name.endsWith('.js') ? [path.join(dir, e.name)] : []);
}

test('SC-ESN-00: the audit covers every emptyHeading call site under src/, and exclusions carry their reason', () => {
  const found = [];
  for (const f of walk(SRC)) {
    const rel = path.relative(SRC, f).split(path.sep).join('/');
    if (rel === 'components/ui/DataState.js' || rel === 'components/dashboard/home/DashboardCard.js') continue; // wrappers
    for (const m of fs.readFileSync(f, 'utf8').matchAll(/emptyHeading="([^"]+)"/g)) found.push(`${rel}::${m[1]}`);
  }
  const audited = AUDIT.map((a) => `${a.file}::${a.heading}`);
  expect(found.sort()).toEqual(audited.sort()); // an unaudited (or renamed) empty state fails here
  expect(found).toHaveLength(20);

  // Headings follow the v1.8 pattern: no trailing period
  for (const a of AUDIT) expect(a.heading.endsWith('.')).toBe(false);

  // Exactly two exclusions, each with a stated reason, and each really has no action of its own
  const excluded = AUDIT.filter((a) => a.kind === 'excluded');
  expect(excluded.map((e) => e.file).sort()).toEqual([
    'components/dashboard/home/AiDailyBriefing.js', 'components/dashboard/home/WhatsNewCard.js']);
  for (const e of excluded) {
    expect(e.reason.length).toBeGreaterThan(10);
    const src = fs.readFileSync(path.join(SRC, e.file), 'utf8');
    expect(src).not.toMatch(/emptyAction=/); // still nothing a user could do to populate it
  }

  // Every page-level new action uses the shared component and the "<Verb> <object>" label rule
  for (const a of AUDIT.filter((x) => x.kind === 'page' && !x.existing)) {
    expect(a.action.split(' ').length).toBeGreaterThanOrEqual(2);
    expect(a.action.split(' ').length).toBeLessThanOrEqual(4);
    expect(a.action.endsWith('.')).toBe(false);
    expect(fs.readFileSync(path.join(SRC, a.file), 'utf8')).toContain('EmptyStateAction');
  }
});

// The empty region is the container DataState renders around the heading, action included.
const region = (page, heading) => page.getByText(heading, { exact: true }).locator('xpath=..');
// One action = an anchor, or a button not already nested inside an anchor (Positions wraps a
// <Button> in a <Link>: one visible action, two DOM elements).
const actions = (page, heading) => region(page, heading).locator('xpath=.//a | .//button[not(ancestor::a)]');

// ---------------------------------------------------------------------------
// Page / section empty states
// ---------------------------------------------------------------------------

async function base(page) {
  await page.route(new RegExp(`${API}/`), (route) => route.fulfill(json({ status: 'ok', data: [] })));
}

test('SC-ESN-01: Positions, Trade Plans, Watchlist and Screener (existing actions) keep exactly one action', async ({ page }) => {
  await base(page);
  await page.route(`${API}/positions`, (route) => route.fulfill(json([])));
  await page.goto('/#/Positions');
  await expect(actions(page, 'No open positions')).toHaveCount(1, { timeout: 10000 });
  await expect(actions(page, 'No open positions')).toContainText('Enter First Position');

  await page.route(`${API}/trade-plans`, (route) => route.fulfill(json({ status: 'ok', data: [] })));
  await page.route(`${API}/trade-plans/tags`, (route) => route.fulfill(json({ status: 'ok', data: [] })));
  await page.goto('/#/TradePlans');
  await expect(actions(page, 'No trade plans yet')).toHaveCount(1, { timeout: 10000 });
  await expect(actions(page, 'No trade plans yet')).toContainText('New Trade Plan');

  await page.route(`${API}/watchlist`, (route) => route.request().method() === 'GET'
    ? route.fulfill(json({ status: 'ok', data: [] })) : route.fallback());
  await page.route(`${API}/watchlist/tags`, (route) => route.fulfill(json({ status: 'ok', data: [] })));
  await page.goto('/#/Watchlist');
  await expect(actions(page, 'Your watchlist is empty')).toHaveCount(1, { timeout: 10000 });
  await expect(actions(page, 'Your watchlist is empty')).toContainText('Add Ticker');
});

test('SC-ESN-02: Notifications empty state offers "Review alert settings" -> Notification Preferences', async ({ page }) => {
  await base(page);
  await page.route(/\/notifications\?page=/, (route) => route.fulfill(json({ status: 'ok', data: { notifications: [], has_more: false } })));
  await page.goto('/#/notifications');
  const acts = actions(page, 'No notifications yet');
  await expect(acts).toHaveCount(1, { timeout: 10000 });
  await expect(acts).toHaveText('Review alert settings');
  await expect(acts).toHaveAttribute('href', '#/notifications/preferences');
  await acts.click();
  await expect(page).toHaveURL(/#\/notifications\/preferences/);
});

test('SC-ESN-03: Screener empty states — "No screener results yet" and "No regime history yet" each have one action; the latter runs the screener', async ({ page }) => {
  await base(page);
  let ran = 0;
  await page.route(`${API}/screener/regime-distribution**`, (route) =>
    route.fulfill(json({ ok: true, data: { window: '30d', run_count: 0, total_observations: 0, risk_on_count: 0, risk_off_count: 0, risk_on_pct: 0, risk_off_pct: 0 } })));
  await page.route(`${API}/screener/results**`, (route) =>
    route.fulfill(json({ results: [], run_id: null, run_timestamp: null, total: 0, limit: 200, offset: 0 })));
  await page.route(`${API}/screener/run`, (route) => { ran += 1; return route.fulfill(json({ ok: true, data: { run_id: 'r', status: 'accepted' } }, 202)); });
  await page.goto('/#/Screener');

  await expect(actions(page, 'No screener results yet')).toHaveCount(1, { timeout: 10000 });
  await expect(actions(page, 'No screener results yet')).toContainText('Run Screener');
  const regime = actions(page, 'No regime history yet');
  await expect(regime).toHaveCount(1);
  await expect(regime).toHaveText('Run the screener');
  await regime.click();
  await expect.poll(() => ran, { timeout: 5000 }).toBeGreaterThan(0);
});

function trades(n) {
  return Array.from({ length: n }, (_, i) => {
    const d = new Date(Date.now() - i * 86400000).toISOString().slice(0, 10);
    return { id: `t${i}`, ticker: 'AAPL', market: 'US', entry_date: d, exit_date: d, pnl: i % 2 ? -50 : 100, pnl_pct: i % 2 ? -2 : 5 };
  });
}
async function mockTrades(page, n) {
  await page.route(`${API}/trades`, (route) =>
    route.fulfill(json({ status: 'ok', data: { total_trades: n, win_rate: 50, total_pnl: 0, trades: trades(n) } })));
}

test('SC-ESN-04: Performance Analytics "Not enough trades" offers "Log a trade" -> Trade Entry', async ({ page }) => {
  await base(page);
  await mockTrades(page, 2);
  await page.goto('/#/PerformanceAnalytics');
  const acts = actions(page, 'Not enough trades');
  await expect(acts).toHaveCount(1, { timeout: 10000 });
  await expect(acts).toHaveText('Log a trade');
  await expect(acts).toHaveAttribute('href', '#/TradeEntry');
});

test('SC-ESN-05: Trade Plan Completion Rate empty state offers "Create a trade plan" and keeps a period-free heading', async ({ page }) => {
  await base(page);
  await mockTrades(page, 12); // clears the analytics "enough trades" gate so the section mounts
  await page.route(new RegExp(`${API}/analytics/trade-plan-completion-rate`), (route) =>
    route.fulfill(json({ status: 'ok', data: { plans_created: 0, plans_completed: 0, plans_abandoned: 0, completion_rate: null, abandoned_pct: null } })));
  await page.goto('/#/PerformanceAnalytics');
  const section = page.getByTestId('trade-plan-completion-rate-section');
  await expect(section.getByText('No trade plans created yet', { exact: true })).toBeVisible({ timeout: 10000 });
  const acts = section.locator('[data-testid="empty-state-action"]');
  await expect(acts).toHaveCount(1);
  await expect(acts).toHaveText('Create a trade plan');
  await expect(acts).toHaveAttribute('href', '#/TradePlan');
});

test('SC-ESN-06: Trade History calendar empty state offers "View open positions" -> Positions', async ({ page }) => {
  await base(page);
  await page.route(`${API}/trades`, (route) => route.fulfill(json({ status: 'ok', data: { trades: [] } })));
  await page.goto('/#/TradeHistory');
  const calendarToggle = page.getByRole('button', { name: 'Calendar' });
  await expect(calendarToggle).toBeVisible({ timeout: 10000 });
  await calendarToggle.click();
  const acts = actions(page, 'No closed trades yet');
  await expect(acts).toHaveCount(1, { timeout: 10000 });
  await expect(acts).toHaveText('View open positions');
  await expect(acts).toHaveAttribute('href', '#/Positions');
});

// ---------------------------------------------------------------------------
// Dashboard cards: the card's own `to` link is the next action (no second inner CTA)
// ---------------------------------------------------------------------------

test('SC-ESN-11: all 9 dashboard cards render their empty state inside their own `to` link, with no inner action', async ({ page }) => {
  await base(page);
  await page.route(`${API}/signals`, (route) => route.fulfill(json([])));
  await page.route(`${API}/positions`, (route) => route.fulfill(json([])));
  await page.route(`${API}/positions/grace-period-alerts`, (route) => route.fulfill(json({ status: 'ok', data: [] })));
  await page.route(`${API}/trades`, (route) => route.fulfill(json({ status: 'ok', data: { trades: [] } })));
  await page.route(new RegExp(`${API}/portfolio/red-flag-journal`), (route) =>
    route.fulfill(json({ status: 'ok', data: { total: 0, page: 1, page_size: 1, items: [] } })));
  await page.route(new RegExp(`${API}/analytics/arc5-compliance`), (route) =>
    route.fulfill(json({ status: 'ok', data: { period: '7d', validation_pass_rate_by_rule: {}, events_per_week: null, override_rate: null, top_rule_breach: null, trade_plan_adherence_rate: null } })));
  await page.goto('/#/DashboardHome');

  for (const card of AUDIT.filter((a) => a.kind === 'card')) {
    const link = page.locator('a', { has: page.getByText(card.heading, { exact: true }) }).first();
    await expect(link, `${card.title}: empty state inside a link`).toBeVisible({ timeout: 15000 });
    await expect(link, `${card.title}: link target`).toHaveAttribute('href', `#${card.to}`);
    await expect(link.getByText(card.title, { exact: true }), `${card.title}: card title`).toBeVisible();
    // no second, inner CTA competing with the card's own click-through (§2.1)
    await expect(link.locator('button, a')).toHaveCount(0);
  }
});
