"""
strategy_engine.backtest() golden-file regression test — ST-01b (EPIC-01, v9.7,
BLG-FEAT-74, F3 extraction).

`docs/product/decisions/po05_replay_scope_confirmation.md` §5 requires: "A golden-file
regression test proves backtest()'s trade output is unchanged; the golden file is
generated from the pre-refactor code on main, not from the refactored code."

`tests/fixtures/strategy_engine_backtest_golden.json` was generated by running the
pre-refactor `backtest()` (the version on `main` before this story extracted
`is_risk_on`/`compute_active_atr_mult`/`compute_initial_stop` into module-level
functions) against a fixed synthetic price/regime fixture, across all three
`stop_loss_mode` values, one of which (`EEE`, halted from day 300) exercises the
ATR = 0 / flat-series stop path. This test re-runs the *current* (refactored)
`backtest()` against the identical fixture and asserts byte-identical trade output —
not just a matching count, but every field of every trade, in order.

If this test ever needs to be regenerated (a genuine, intentional change to
`backtest()`'s behaviour, not this story's refactor), regenerate the fixture from the
pre-change code, never from the changed code — a golden file generated from the
changed code cannot catch a regression in that same change.
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "backend"))

from services.strategy_engine import backtest, compute_atr, compute_risk_on, compute_signals  # noqa: E402

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "strategy_engine_backtest_golden.json"
N_DAYS = 400


def _build_fixture():
    """Deterministic synthetic universe: 5 tickers (2 UK), one (EEE) halted (zero
    returns) from day 300 onward to exercise the ATR = 0 flat-series stop path."""
    dates = pd.bdate_range("2023-01-02", periods=N_DAYS)
    tickers = ["AAA", "BBB.L", "CCC", "DDD.L", "EEE"]

    def make_series(seed, start=100.0, drift=0.0003, vol=0.02, halt_from=None):
        r = np.random.default_rng(seed).normal(drift, vol, N_DAYS)
        if halt_from is not None:
            r[halt_from:] = 0.0
        return start * np.cumprod(1 + r)

    prices = pd.DataFrame(
        {t: make_series(i, halt_from=(300 if t == "EEE" else None)) for i, t in enumerate(tickers)},
        index=dates,
    )
    spy = pd.Series(make_series(100), index=dates)
    ftse = pd.Series(make_series(101), index=dates)
    return prices, spy, ftse


def _normalise(records):
    """Match the JSON round-trip the golden fixture went through: Timestamp -> ISO
    string, numpy scalar -> plain Python."""
    out = []
    for rec in records:
        row = {}
        for k, v in rec.items():
            if isinstance(v, pd.Timestamp):
                row[k] = v.isoformat()
            elif isinstance(v, np.floating):
                row[k] = float(v)
            elif isinstance(v, np.integer):
                row[k] = int(v)
            elif isinstance(v, np.bool_):
                row[k] = bool(v)
            else:
                row[k] = v
        out.append(row)
    return out


@pytest.fixture(scope="module")
def golden():
    return json.loads(FIXTURE_PATH.read_text())


@pytest.mark.parametrize("mode", ["simple", "tiered", "profit_lock"])
def test_backtest_trades_unchanged_after_f3_extraction(mode, golden):
    prices, spy, ftse = _build_fixture()
    atr = compute_atr(prices)
    volatility = prices.pct_change().rolling(60).std()
    regime_us = compute_risk_on(spy)
    regime_uk = compute_risk_on(ftse)
    signals = compute_signals(prices, lookback=60, top_n=3)

    pv, returns, trades_df = backtest(
        signals, prices, volatility, atr, regime_us, regime_uk,
        rebalance_freq="ME", atr_mult=2, min_hold_days=7, risk_off_mode="single",
        stop_loss_mode=mode, initial_atr_mult=5, profit_atr_mult=2,
        as_of=pd.Timestamp("2024-06-01"),
    )
    trades = _normalise(trades_df.to_dict(orient="records"))
    expected = golden[mode]

    assert len(trades) == expected["n_trades"] > 0, f"{mode}: fixture must produce real trades to be a meaningful regression guard"
    assert trades == expected["trades"], f"{mode}: backtest() trade output changed after the F3 extraction"
    assert float(pv.iloc[-1]) == pytest.approx(expected["final_pv"], abs=1e-9), f"{mode}: final portfolio value changed"


def test_fixture_covers_the_atr_zero_flat_series_path(golden):
    """EEE is halted (zero daily return) from day 300 -- confirms the fixture actually
    exercises backtest()'s ATR = 0 -> immediate-stop path (compute_initial_stop /
    compute_active_atr_mult with atr_at_entry == 0), not just the common case."""
    any_eee_trade = any(t["Ticker"] == "EEE" for mode in golden.values() for t in mode["trades"])
    assert any_eee_trade, "fixture must include at least one EEE (halted-series) trade"
